### ISSUE TITLE
Incompatibility with Diet mod

### ISSUE THREAD

**Issue by mosharky** [Apothicon02/Apothitweaks#2]
[Crash](https://mclo.gs/FbPbCQE)

The crash happened while loading into a new singleplayer world

**Comment by mosharky** [comment]
I'm assuming it's incompatible with the hunger overhaul module, I haven't tested if it works with that disabled though

**Comment by Apothicon02** [comment]
99% sure it will work if you disable the hunger overhaul in the config.
